### PR TITLE
Fix bug with role.organization translation

### PR DESCRIPTION
**Pull request by ianwallen**
Fix bug related to issues #18

### CODE REVIEW

**Comment by josegar74** [comment]
@ianwallen are the PR for 3.8.x branch relevant or should be moved to 3.10.x?

**Comment by ianwallen** [comment]
Most of the pr for 3.8.x are for bugs that also exists in 3.10.x so yes they should be merged as well.  If you want to review/approve them for 3.8.x, I can double check that the same bug exists in 3.10.x and I will do a cherry pick.

**Comment by ianwallen** [comment]
Note that most of the pr are linked to an issue which explain the bug so it is easy to test in 3.10.x to see if it exists.

**Review by josegar74 — APPROVED** [review]
Tested, working fine.

**Pull request merged**
