### PR TITLE
Removing unnecessary EC thesaurus

### PR DESCRIPTION
**Pull request by geothorne**
As per issue 53: https://github.com/metadata101/iso19139.ca.HNAP/issues/53

EC has done a review of ECCC current thesaurus and have identified several rdf that not longer valid. 

* [x] EC_Content_Scope
* [x] EC_Data_Usage_Scope
* [x] EC_Government_Names
* [x] EC_Information_Category
* [x] EC_Org_Names
* [x] EC_Resource_ContentTypes

### CODE REVIEW

**Comment by jodygarnett** [comment]
@davidblasby is working on some of these (and other files) addressing multi-lingual titles. We should coordinate activities here to prevent conflicts.

**Comment by jodygarnett** [comment]
@geothorne this PR has conflicts, since this only consists of deletes it may be worth just redoing the work?

**Comment by geothorne** [comment]
We will need to review and discuss.... I booked a meeting for tomorrow with
you Jody. :)
Chris

**Comment by davidblasby** [comment]
https://github.com/metadata101/iso19139.ca.HNAP/pull/75

**Comment by davidblasby** [comment]
@geothorne - I had to re-add EC_Org_Names (renamed to GC_Org_Names) since it is used in the Organization Selector.

**Comment by davidblasby** [comment]
I had to re-add EC_Government_Names (renamed to GC_Government_Names) because it was being used in validation

**Comment by jodygarnett** [comment]
I understand that this PR is covered by https://github.com/metadata101/iso19139.ca.HNAP/pull/75 above and am marking it closed.

**Pull request closed without merging**
