### PR TITLE
Remove gmd:locale for main language. Fixes  #224

### LINKED ISSUE #224: Remove duplicate gmd:locale
We have run into some records, which validate successfully, produce strange behaviour when published to FGP.

The records have the main language listed as a `gmd:locale` resulting in two `gmd:locale` elements. Although this is a valid record, this trips up the FGP validation and user interface. 

Updating the record  to remove the `gmd:locale` for the document primary language resolves the issue.

```xml
<gmd:locale>
      <gmd:PT_Locale id="fra">
         <gmd:languageCode>
            <gmd:LanguageCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116"
                              codeListValue="fra">French; Français</gmd:LanguageCode>
         </gmd:languageCode>
         <gmd:country>
            <gmd:Country codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_117"
                         codeListValue="CAN">Canada; Canada</gmd:Country>
         </gmd:country>
         <gmd:characterEncoding>
            <gmd:MD_CharacterSetCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_95"
                                     codeListValue="RI_458">utf8; utf8</gmd:MD_CharacterSetCode>
         </gmd:characterEncoding>
      </gmd:PT_Locale>
  </gmd:locale>

  <gmd:locale>
      <gmd:PT_Locale id="eng">
         <gmd:languageCode>
            <gmd:LanguageCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116"
                              codeListValue="eng">English; Anglais</gmd:LanguageCode>
         </gmd:languageCode>
         <gmd:country>
            <gmd:Country codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_117"
                         codeListValue="CAN">Canada; Canada</gmd:Country>
         </gmd:country>
         <gmd:characterEncoding>
            <gmd:MD_CharacterSetCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_95"
                                     codeListValue="RI_458">utf8; utf8</gmd:MD_CharacterSetCode>
         </gmd:characterEncoding>
      </gmd:PT_Locale>
  </gmd:locale>
```

----

Checking https://metadata101.github.io/schemas/fgp/hnap/HNAP.html has limited guidance on ``gmd:locale``:

> Guideline: NAP registered code lists based on ISO 639.2 alpha-3 terminology codes for language (eng=English, fra=French) and ISO 3166-1 alpha-3 codes (CAN=Canada) for countries shall be used to describe locale and character encoding shall be set to "utf8; utf8", as shown in the following example:
>
> ```
> <gmd:locale>
>   <gmd:PT_Locale id="fra">
>     <gmd:languageCode>
>       <gmd:LanguageCode codeListValue="fra" codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116">
>         French; Français
>       </gmd:LanguageCode>
>     </gmd:languageCode>
>     <gmd:country>
>       <gmd:Country codeListValue="CAN" codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_117">
>         Canada; Canada
>       </gmd:Country>
>     </gmd:country>
>     <gmd:characterEncoding>
>       <gmd:MD_CharacterSetCode codeListValue="RI_458" codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_95">
>         utf8; utf8
>       </gmd:MD_CharacterSetCode>
>     </gmd:characterEncoding>
>   </gmd:PT_Locale>
> </gmd:locale>
> ```

----

Discussion:

* We can fix the editor using `update-fixed-info` to remove the `gmd:locale` for the main language so it appears as expected for FGP. For this to work with the core-components inflate would add the `gmd:locale` for the primary langugage for the edit session.

* Alternatively we can create an `xsl` fix for FGP / HNAP 3.6 to remove the `gmd:locale` for the primary langauge during import

### PR DESCRIPTION
**Pull request by josegar74**

### CODE REVIEW

**Comment by ianwallen** [comment]
This may only be a partial fix to the problem.
I have added a comment to the issue https://github.com/metadata101/iso19139.ca.HNAP/issues/224#issuecomment-872909766
If we decide that this is still required based on these comments then I can do a review.

**Review by ianwallen — APPROVED** [review]

**Review by jodygarnett — COMMENTED** [review]
Thanks!

**Comment by jodygarnett** [comment]
To test I note that the editor xml view shows the `3b0ccbbe-e0f7-4e6f-a6aa-8b327c69a169` sample data with:
```
   <gmd:language>
      <gco:CharacterString>fra; CAN</gco:CharacterString>
   </gmd:language>
```
```
   <gmd:locale>
      <gmd:PT_Locale id="eng">
         <gmd:languageCode>
            <gmd:LanguageCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116"
                              codeListValue="eng">English; Anglais</gmd:LanguageCode>
         </gmd:languageCode>
         <gmd:country>
            <gmd:Country codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_117"
                         codeListValue="CAN">Canada; Canada</gmd:Country>
         </gmd:country>
         <gmd:characterEncoding>
            <gmd:MD_CharacterSetCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_95"
                                     codeListValue="RI_458">utf8; utf8</gmd:MD_CharacterSetCode>
         </gmd:characterEncoding>
      </gmd:PT_Locale>
  </gmd:locale>
   <gmd:locale>
      <gmd:PT_Locale id="fra">
         <gmd:languageCode>
            <gmd:LanguageCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_116"
                              codeListValue="fra">French; Français</gmd:LanguageCode>
         </gmd:languageCode>
         <gmd:country>
            <gmd:Country codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_117"
                         codeListValue="CAN">Canada; Canada</gmd:Country>
         </gmd:country>
         <gmd:characterEncoding>
            <gmd:MD_CharacterSetCode codeList="http://nap.geogratis.gc.ca/metadata/register/napMetadataRegister.xml#IC_95"
                                     codeListValue="RI_458">utf8; utf8</gmd:MD_CharacterSetCode>
         </gmd:characterEncoding>
      </gmd:PT_Locale>
   </gmd:locale>
```

After saving the xml download has primary language `fra; CAN` and gmd:locale `eng`

**Comment by jodygarnett** [comment]
Marked as milestone 3.10.7 to reflect cherry-pick of this fix to the 3.10.x branch

**Pull request merged**
