### PR TITLE
removed getMappedLang as it was not longer needed since the 3.10.2 co…

### PR DESCRIPTION
**Pull request by ianwallen**
Removed getMappedLang as it was not longer needed for the 3.10.2

Also getMappedLang seems to break an api test in the unit test. I did not identify why it was causing the issue but when removed, it seems to have fixed the issue.

### CODE REVIEW

**Comment by josegar74** [comment]
@ianwallen I think probably due to the merge first of https://github.com/metadata101/iso19139.ca.HNAP/pull/34 has caused a conflict, please check to update, apologies.

**Comment by ianwallen** [comment]
The conflict have been fixed.

**Comment by ianwallen** [comment]
@davidblasby . This change reverts the changes that you had previously done to get-iso19139.ca.HNAP-other-languages-as-json.  The problem what that it was not getting the language correctly in the first place. Now that 3.10.2 has better language handling it should no longer get bad language values so there is no need to distinct the values or use the getMappedLang.

I'm not sure if you had a specific testcase that you were using which caused bad values in the language?

**Comment by davidblasby** [comment]
@ianwallen 

The test case is very easy - just look at the configuration sent to the browser.  
I just use the browser's dev tool and look at the "editor?" request.

  data-gn-multilingual-field="{&#34;eng&#34;:&#34;#eng&#34;,&#34;fre&#34;:&#34;#fra&#34;}"

^^ you'll see lots like this

I then just decode it here - https://codebeautify.org/html-decode-string

  data-gn-multilingual-field="{"eng":"#eng","fre":"#fra"}"

Test case -- it should just have "eng" and "fre" in the dictionary.  "eng" should NOT appear twice.

**Comment by ianwallen** [comment]
@davidblasby 
Looks like I had forgotten to apply the switch from fra to fre.
I have made the corrections and I now get the following values which seems to match the expectations of what you had posted.
 
data-gn-multilingual-field="{"eng":"#eng","fre":"#fra"}"

**Comment by davidblasby** [comment]
@ianwallen - awesome!

**Review by josegar74 — APPROVED** [review]
Code changes look fine, thanks.

**Pull request merged**
