### PR TITLE
Transifex instructions and use

### PR DESCRIPTION
**Pull request by jodygarnett**
Working with @pvgenuchten to set this up as an experiment.

### CODE REVIEW

**Comment by comradekingu** [comment]
@jodygarnett Could you consider putting it on any variant of Weblate instead? That way people can contribute without all the spying scripts.

**Comment by jodygarnett** [comment]
I would be happy to consider that, https://weblate.org/en/ sounds pretty good!

**Review by ianwallen — APPROVED** [review]

**Comment by comradekingu** [comment]
@jodygarnett Setting it up on https://hosted.weblate.org/hosting/ is easy enough.

**Comment by jodygarnett** [comment]
Closing this; transifex is looking too complicated.

Going to use another [service](https://www.deepl.com/translator) to translate the RST files directly for the user manual.

**Pull request merged**
