### PR TITLE
Validation error showing for temporal extend.

### PR DESCRIPTION
**Pull request by wangf1122**
Here is after the fix.

image

### CODE REVIEW

**Comment by wangf1122** [comment]
Issue link:

https://github.com/metadata101/iso19139.ca.HNAP/issues/210

**Review by ianwallen — COMMENTED** [review]
I don't believe we can remove the `templateModeOnly="true"`
When you do that the date selector is just a generic date selector.
We need the ability to be able to enter dates like the following.
image

**Comment by wangf1122** [comment]
> I don't believe we can remove the `templateModeOnly="true"`
> When you do that the date selector is just a generic date selector.
> We need the ability to be able to enter dates like the following.
> image

@ianwallen 

The templateModeOnly has brought us another issue. The temporal element can never be removed. I think we should just get rid of that mode. Then add the date picker in this xsl. I had some luck to add it and it's doable. But will probably take long time. 

Can we do a short pull request to just give short relief (I will commit some code to this branch to force using datetime i.e. 2021-05-19T16:36:00)? Then we will investigate the date-picker option after?

**Comment by wangf1122** [comment]
Come with final solution. The date-picker is moved into layout-custom-fields.xsl. It has the ability to swap among year, year-monty, and full date-time mode. Validation text works too.

image

**Comment by josegar74** [comment]
The validation message works fine, but when I set a value, for example in the `Begin date` and click `Save metadata`, the following error is displayed:

error-save-temporal-extent

**Comment by wangf1122** [comment]
@josegar74 

This is expected. We are passing string as is without node to <beginPosition> and <endPosition> as XMLFragment. So Geonetwork-Core should support String to parse. Here is the pull request for Geonetwork Core module. https://github.com/geonetwork/core-geonetwork/pull/5746

So they have dependency with each other.

**Comment by jodygarnett** [comment]
Any update or discusion needed here?

**Comment by wangf1122** [comment]
@jodygarnett 

This change has a dependency change in Geonetwork itself which is https://github.com/geonetwork/core-geonetwork/pull/5746. It is not approved yet. So we should not approve this change until Geonetwork community approves it.

**Comment by josegar74** [comment]
@wangf1122 I see it's send this `_X249: 2021-07-26`. The field name starting with `_X` is used for xml fragments. Why is not send the value for the field like `_249: 2021-07-26` as other "simple" values?

It seems related to this: https://github.com/metadata101/iso19139.ca.HNAP/pull/211/files#diff-7a655927f8b146f5aeab45cbd707980efccd2f738f9a17c502592d19e3e9ae4fR85

Checking if configured like the following, it's not required the change in core GeoNetwork:

```
 data-element-ref="{concat('_', gn:element/@ref)}"
 ```

**Comment by josegar74** [comment]
@wangf1122 I've tested previous change and looks ok, without requiring the change in https://github.com/geonetwork/core-geonetwork/pull/5746, can you double check?

**Comment by wangf1122** [comment]
@josegar74 

I tested and confirmed the simple value mode  data-element-ref="{concat('_', gn:element/@ref)}"
  works. I will take https://github.com/geonetwork/core-geonetwork/pull/5746 off. Please just do merging for metadata101 part. Thanks

**Review by josegar74 — APPROVED** [review]

**Pull request merged**
