### PR TITLE
Use dates from the thesaurus file if exists instead of file system last modified date from thesaurusDate

### PR DESCRIPTION
**Pull request by wangf1122**
This is to fix the issue https://github.com/metadata101/iso19139.ca.HNAP/issues/308

Also depends on this PR https://github.com/geonetwork/core-geonetwork/pull/6972

Once Geonetwork passed isFilesystemDate flag into the HNAP schema. HNAP will be able to parse it or discard it.

### CODE REVIEW

**Comment by ianwallen** [comment]
Related to #329

**Comment by josegar74** [comment]
Probably relevant to update https://github.com/metadata101/iso19139.ca.HNAP/blob/3.12.x/src/main/config/codelist/local/thesauri/theme/GC_Core_Subject.rdf as part of this pull request with the relevant dates.

**Comment by wangf1122** [comment]
Yes, the thesaurus file itself needs to be updated. I was thinking to do in a separate PR or if you prefer, I can do into this PR. I am also trying to define what date to put into this file.

**Comment by ianwallen** [comment]
@josegar74 

> Probably relevant to update https://github.com/metadata101/iso19139.ca.HNAP/blob/3.12.x/src/main/config/codelist/local/thesauri/theme/GC_Core_Subject.rdf as part of this pull request with the relevant dates.

This is related to the following issue
Related to https://github.com/metadata101/iso19139.ca.HNAP/issues/329

Once the correct date is identified then we can create a new PR to apply the changes.

**Review by ianwallen — APPROVED** [review]
It would be nice if the `<gmd:date>` was created by a function so that it would remove a lot of duplicated code however overall - I have tested and it works as expected.

**Comment by ianwallen** [comment]
If we don't want to wait for related issue https://github.com/metadata101/iso19139.ca.HNAP/issues/329 , then we can do as @josegar74 suggested and just use the existing values.  And when issue #329 identifies the correct dates then we can create another PR to apply the correct dates.

```
      <dcterms:issued>2004</dcterms:issued>
      <dcterms:created>2016-07-04</dcterms:created>

```

**Comment by wangf1122** [comment]
I added the default date to the GC_Core thesaurus file. Also group the logics to a single function. Tested and works fine. @ianwallen

**Pull request merged**
