### PR TITLE
Spatial representation type should not be mandatory

### LINKED ISSUE #299: Spatial representation type should not be mandatory
It should be possible to create a record without the Spatial representation type

But it keeps adding the Spatial representation type if it is deleted.

### PR DESCRIPTION
**Pull request by josegar74**
Fixes #299

### CODE REVIEW

**Comment by wangf1122** [comment]
Edited: I misunderstood it. This field still has no empty option to select from and always defaulted to Vector

image

**Comment by josegar74** [comment]
@wangf1122, if no need of the element, you can remove it now. Previously when removed, was re-added again.

**Comment by wangf1122** [comment]
> @wangf1122, if no need of the element, you can remove it now. Previously when removed, was re-added again.

Yes, It can be removed now as 
image


I also checked shematron validation and no related error complain about the removal. Looking good

**Review by ianwallen — APPROVED** [review]

**Comment by jodygarnett** [comment]
See https://schemas.metadata.geo.ca/hnap/2.3.1/HNAP.md#footnote2

**Pull request merged**
