### PR TITLE
adding setting for controlling org name GUI

### PR DESCRIPTION
**Pull request by davidblasby**
This allows for a setting to control if the keyword-picker based org name selector is used or not.

See https://github.com/geonetwork/core-geonetwork/pull/4631

### CODE REVIEW

**Comment by ianwallen** [comment]
Maybe I'm missing something but should there not be a fr-schema-iso19139.ca.HNAP.json file included as well?

**Comment by ianwallen** [comment]
This pull request should not be approved until [#4631](https://github.com/geonetwork/core-geonetwork/pull/4631) has been approved.

**Comment by davidblasby** [comment]
yes - I can use google translate (or something) to do the translation for the fr- file.

**Comment by davidblasby** [comment]
added french translation file

**Review by josegar74 — APPROVED** [review]
Tested, working file, I added some comments in the related https://github.com/geonetwork/core-geonetwork/pull/4631 to review, before merge this one.

In any case, if you think can be merged without requiring first to have merged  https://github.com/geonetwork/core-geonetwork/pull/4631, let me know.

**Pull request merged**
